arobases_sylius_customer_support_plugin_admin_customer_support_index:
  path: /admin/customer_support
  methods: [GET]
  defaults:
    _controller: arobases_sylius_customer_support_plugin.controller.customer_support::indexAction
    _sylius:
      permission: true
      section: admin
      grid: arobases_admin_customer_support



arobases_sylius_customer_support_plugin_admin_customer_support_update:
  path: /admin/customer_support/{id}/update
  methods: [GET,PUT]
  requirements:
    id: \d+
  defaults:
    _controller: arobases_sylius_customer_support_plugin.controller.customer_support::updateAction
    _sylius:
      permission: true
      section: admin
      redirect: arobases_sylius_customer_support_plugin_admin_customer_support_update
      template: '@ArobasesSyliusCustomerSupportPlugin/Admin/Crud/update.html.twig'
      vars:
        templates:
          form: '@ArobasesSyliusCustomerSupportPlugin/Admin/form.html.twig'

arobases_sylius_customer_support_plugin_admin_customer_support_delete:
  path: /admin/customer_support/{id}/delete
  methods: [DELETE]
  requirements:
    id: \d+
  defaults:
    _controller: arobases_sylius_customer_support_plugin.controller.customer_support::deleteAction
    _sylius:
      permission: true
      section: admin
      redirect: arobases_sylius_customer_support_plugin_admin_customer_support_index

arobases_sylius_customer_support_plugin_admin_customer_support_change_status:
  path: /admin/customer_support/{id}/changeStatus
  methods: [PATCH]
  defaults:
    _controller: Arobases\SyliusCustomerSupportPlugin\Controller\ChangeStatusCustomerSupportController:changeStatus
    _sylius:
      section: admin
      redirect:  arobases_sylius_customer_support_plugin_admin_customer_support_index
