services:
  arobases.listener.admin.menu_builder:
      class: Arobases\SyliusCustomerSupportPlugin\Menu\AdminMenuListener
      tags:
          - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

  Arobases\SyliusCustomerSupportPlugin\Menu\AccountMenuBuilder:
    decorates: sylius.shop.menu_builder.account
    arguments:
      - '@knp_menu.factory'
      - '@event_dispatcher'

  arobases.form.type.shop.order_choice:
    class: Arobases\SyliusCustomerSupportPlugin\Form\Shop\OrderChoiceType
    tags:
      - { name: form.type}
    arguments:
      - '@sylius.repository.order'
      - '@sylius.context.customer'

  arobases.form.type.shop.customer_support:
    class: Arobases\SyliusCustomerSupportPlugin\Form\Shop\CustomerSupportType
    tags:
      - { name: form.type}
    arguments:
      - '@arobases_sylius_customer_support_plugin.uploader.customer_support_answer'
      - '@translator'

  arobases.form.type.shop.customer_support_create:
    class: Arobases\SyliusCustomerSupportPlugin\Form\Shop\CustomerSupportCreateType
    tags:
      - { name: form.type}
    arguments:
      - '@arobases_sylius_customer_support_plugin.uploader.customer_support_answer'
      - '@translator'

  arobases.form.type.admin.customer_support:
    class: Arobases\SyliusCustomerSupportPlugin\Form\Admin\CustomerSupportType
    tags:
      - { name: form.type}
    arguments:
      - '@arobases_sylius_customer_support_plugin.uploader.customer_support_answer'
      - '@translator'

  Arobases\SyliusCustomerSupportPlugin\Controller\ChangeStatusCustomerSupportController:
    tags: ['controller.service_arguments']
    arguments:
      - '@arobases_sylius_customer_support_plugin.repository.customer_support'
      - '@Symfony\Component\Routing\RouterInterface'
      - '@doctrine.orm.default_entity_manager'

  arobases_sylius_customer_support_plugin.provider.file_name_provider:
    class:  Arobases\SyliusCustomerSupportPlugin\Files\Provider\FileNameProvider
    arguments:
      - '@filesystem'

  arobases_sylius_customer_support_plugin.uploader.customer_support_answer:
    class: Arobases\SyliusCustomerSupportPlugin\Files\Uploader\CustomerSupportAnswerUploader
    arguments:
      - '@filesystem'
      - '@arobases_sylius_customer_support_plugin.provider.file_name_provider'
      - '%kernel.project_dir%/public/'
      - 'media/image/'

  arobases_sylius_customer_support_plugin.email_manager.send_notification_answer_email_manager:
    class:  Arobases\SyliusCustomerSupportPlugin\EmailManager\SendNotificationAnswerEmailManager
    arguments:
      - '@sylius.email_sender'
      - '@sylius.context.locale'

  Arobases\SyliusCustomerSupportPlugin\EventListener\CustomerSupportListener:
    class: Arobases\SyliusCustomerSupportPlugin\EventListener\CustomerSupportListener
    tags:
      - { name: kernel.event_listener , event: arobases_sylius_customer_support_plugin.customer_support.post_update, method: postUpdate }
      - { name: kernel.event_listener , event: arobases_sylius_customer_support_plugin.customer_support.post_create, method: postCreate }
    arguments:
      - '@arobases_sylius_customer_support_plugin.email_manager.send_notification_answer_email_manager'
